stages:
  - test
  - build
  - deploy
build:
  stage: build
  image: "node:8-alpine"
  script:
    - apk add openssh git
    - eval `ssh-agent -s`
    - chmod 600 $SSH_KEY
    - ssh-add $SSH_KEY
    - echo -e "Host *\n  StrictHostKeyChecking no" > /etc/ssh/ssh_config
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/
    expire_in: 1 week