stages:
  - build
  - dockerize
build:
  stage: build
  image: "node:8-alpine"
  script:
    - apk add openssh git
    - eval `ssh-agent -s`
    - chmod 600 $SSH_KEY
    - ssh-add $SSH_KEY
    - echo -e "Host *\n  StrictHostKeyChecking no" > /etc/ssh/ssh_config
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
dockerize:
  stage: dockerize
  image: "google/cloud-sdk:255.0.0"
  script:
    - systemctl start docker
    - gcloud auth activate-service-account --key-file=$GCR_SA_KEY_FILE
    - gcloud auth configure-docker
    - docker build -t gcr.io/trailwebsite-1563630921547/trail-website/client .
    - docker push gcr.io/trailwebsite-1563630921547/trail-website/client